#!/usr/bin/env node

import { execSync, spawn } from "node:child_process";
import { createInterface } from "node:readline";
import { writeFileSync, readFileSync, existsSync, copyFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

const BLUE = "\x1b[34m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const DIM = "\x1b[2m";
const BOLD = "\x1b[1m";
const RESET = "\x1b[0m";

function banner() {
  console.log(`
${BLUE}${BOLD}  ____  _                                       
 / ___|| |__  _ __ __ ___   ____ _ _ __  _ __  
 \\___ \\| '_ \\| '__/ _\` \\ \\ / / _\` | '_ \\| '_ \\ 
  ___) | | | | | | (_| |\\ V / (_| | | | | | | |
 |____/|_| |_|_|  \\__,_| \\_/ \\__,_|_| |_|_| |_|${RESET}

${DIM}  Multi-agent voice AI platform${RESET}
`);
}

function rl() {
  return createInterface({ input: process.stdin, output: process.stdout });
}

function ask(prompt, fallback) {
  return new Promise((resolve) => {
    const r = rl();
    const suffix = fallback ? ` ${DIM}(${fallback})${RESET}` : "";
    r.question(`  ${prompt}${suffix}: `, (answer) => {
      r.close();
      resolve(answer.trim() || fallback || "");
    });
  });
}

function randomHex(bytes) {
  return randomBytes(bytes).toString("hex");
}

function dockerAvailable() {
  try {
    execSync("docker compose version", { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

async function main() {
  banner();

  if (!dockerAvailable()) {
    console.error(
      `${YELLOW}  Docker with Compose plugin is required but was not found.${RESET}\n` +
        `  Install Docker Desktop: https://docs.docker.com/get-docker/\n`
    );
    process.exit(1);
  }

  console.log(`${BOLD}  Configuration${RESET}\n`);
  console.log(
    `${DIM}  LiveKit credentials are required for voice sessions.${RESET}`
  );
  console.log(
    `${DIM}  Get a free account at https://livekit.io/${RESET}\n`
  );

  const livekitUrl = await ask("LiveKit URL", "wss://your-project.livekit.cloud");
  const livekitKey = await ask("LiveKit API Key");
  const livekitSecret = await ask("LiveKit API Secret");

  const encryptionKey = randomHex(32);
  const jwtSecret = randomHex(32);

  console.log(
    `\n${DIM}  Auto-generated ENCRYPTION_KEY and JWT_SECRET.${RESET}\n`
  );

  const envContent = [
    "# Generated by create-shravann",
    `LIVEKIT_URL=${livekitUrl}`,
    `LIVEKIT_API_KEY=${livekitKey}`,
    `LIVEKIT_API_SECRET=${livekitSecret}`,
    `ENCRYPTION_KEY=${encryptionKey}`,
    `JWT_SECRET=${jwtSecret}`,
    "",
  ].join("\n");

  writeFileSync(".env", envContent);
  console.log(`  ${GREEN}Created .env${RESET}`);

  const composeSrc = join(__dirname, "docker-compose.yml");
  if (!existsSync("docker-compose.yml")) {
    copyFileSync(composeSrc, "docker-compose.yml");
    console.log(`  ${GREEN}Created docker-compose.yml${RESET}`);
  }

  console.log(`\n${BOLD}  Starting services...${RESET}\n`);

  const dc = spawn("docker", ["compose", "up", "-d", "--pull", "always"], {
    stdio: "inherit",
  });

  await new Promise((resolve, reject) => {
    dc.on("close", (code) => (code === 0 ? resolve() : reject(code)));
  });

  console.log(`\n${BOLD}  Waiting for API to be ready...${RESET}`);

  let ready = false;
  for (let i = 0; i < 30; i++) {
    try {
      const res = await fetch("http://localhost:8080/health");
      if (res.ok) {
        ready = true;
        break;
      }
    } catch {}
    await new Promise((r) => setTimeout(r, 2000));
    process.stdout.write(".");
  }
  console.log("");

  if (!ready) {
    console.log(
      `\n${YELLOW}  API is taking longer than expected. Check logs with: docker compose logs api${RESET}`
    );
  }

  console.log(`
${GREEN}${BOLD}  Shravann is running!${RESET}

  ${BOLD}Dashboard${RESET}       http://localhost:3000
  ${BOLD}Session App${RESET}     http://localhost:3001
  ${BOLD}API${RESET}             http://localhost:8080

  ${BOLD}Default login${RESET}
  Email:          admin@shravann.local
  Password:       admin
  ${DIM}(You will be asked to change it on first login)${RESET}

  ${DIM}Useful commands:${RESET}
    docker compose logs -f      ${DIM}# follow logs${RESET}
    docker compose down          ${DIM}# stop all services${RESET}
    docker compose down -v       ${DIM}# stop and remove data${RESET}
`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
